### ISSUE TITLE
Be able to mark a show as «Not for children»

### ISSUE THREAD

**Issue by essoen** [Studentmediene/RadioRevolt-API#5]

**Comment by tobinus** [comment]
A bit of context:  
This will be used to inform Itunes and others about whether the show is "explicit" or not. Their definition of "explicit":

> A label issued by media producers that alerts consumers to content that might be inappropriate for children.

Thus, a show about very advanced, technical concepts that could be deemed "not for children" because the subject is very complex, should _not_ be marked as explicit if it has no bad language and no references to drugs or other adult topics. On the other hand, a show which reads aloud children's books, but adds random swearing to each sentence, should be marked as explicit (and thus "not for children"). In short: there's a distinction between "appropriate for children" and "child friendly".

One more point: it is easier to understand checkboxes/flags which are positive and active, so maybe this could be rephrased as "Safe for children".
